### PR TITLE
Remote airflow

### PR DESCRIPTION
**Pull request by cwurtz**

### CODE REVIEW

**Comment by ryw** [comment]
@cwurtz any reason we never merged this? should we now?

**Comment by cwurtz** [comment]
It was never merged because of the problem with getting the airflow plugin working with the mesos executor.  I fixed that around xmas, but this just never got merged.  I need to verify it still works since it's so old, but we can merge it.

**Comment by ryw** [comment]
let's ship this for cloud this milestone, if it's just waiting for the merging of PR

**Comment by ryw** [comment]
@cwurtz we should just close this PR right?

**Comment by cwurtz** [comment]
Yeah, no use spending time on it since it will be replaced

**Pull request closed without merging**
